// A valid test exception
exception exception_valid;
